---
 
- name: Création de la VM
  community.general.proxmox_kvm:
       api_user: "ansible@pam"
       api_password: "ixelles1050"
       api_host: "pve-pxs-sm2u-r5-33"
       node: "{{ proxmox_node }}"
       vmid: "151"
       name: "VM-ubuntu-qcow2"
       ostype: l26
       cores: 4
       sockets: 2
       memory: 4096
       bios: seabios
       machine: q35
       scsihw: virtio-scsi-pci  # Use VirtIO SCSI controller
       net:
         net0: "virtio,bridge=vmbr0,firewall=1,tag=508"
       boot: "order=ide2;scsi0;net0"  # Set boot order with SCSI disk
       ide:
         ide2: "proxmox_nrc_nfs_ds02:iso/ubuntu-24.04.1-live-server-amd64-autoinstall.iso,media=cdrom"
       scsi:
         scsi0: "proxmox_nrc_nfs_ds02:50,format=qcow2"   # Disque principal (50GB)
         scsi1: "proxmox_nrc_nfs_ds02:30,format=qcow2"   # Disque secondaire (30GB)
         scsi2: "proxmox_nrc_nfs_ds02:20,format=qcow2"   # Disque tertiaire (20GB)
       
       state: present
   
- name: Attendre avant de démarrer la VM
  ansible.builtin.pause:
       seconds: 10
   
- name: Démarrer la VM
  community.general.proxmox_kvm:
       api_user: "ansible@pam"
       api_password: "ixelles1050"
       api_host: "pve-pxs-sm2u-r5-33"
       vmid: "151"
       state: started
   
- name: Mettre à jour l'ordre de démarrage après installation
  community.general.proxmox_kvm:
       api_user: "ansible@pam"
       api_password: "ixelles1050"
       api_host: "pve-pxs-sm2u-r5-33"
       node: "{{ proxmox_node }}"
       vmid: "151"
       boot: "order=scsi0;net0"  # Boot from the main SCSI disk after installation
       state: present