---
# tasks file for provision_vm
# tasks/main.yml
#- name: Create VM {{ vm_name }}
 # community.general.proxmox_kvm:
  #  api_user: "root@pam"
   # api_password: "ixelles1050"
    #api_host: "pve-pxs-sm2u-r5-33"
    #node: "{{ node }}"
    #vmid: "{{ vm_id }}"
    #name: "{{ vm_name }}"
    #memory: "{{ memory }}"
    #cores: "{{ cores }}"
    #scsihw: "virtio-scsi-pci"
    #boot: "cdn"
    #ide:
     # ide0: "{{ iso }},media=cdrom" 
    #ostype: "l26"
    #net:
     # net0: "model=virtio,bridge={{ network.bridge }},tag={{ network.vlan }}"
   # state: present
  #delegate_to: localhost

#- name: Generate SCSI mapping
 # set_fact:
  #  scsi_map: >-
   #   {{
    #    dict(
     #     ('scsi' ~ index|string, disk.storage ~ ':' ~ disk.size)
      #    for index, disk in disks | enumerate
     #   )
     # }}

#- name: Add disks to VM
 # community.general.proxmox_kvm:
  #  api_user: "root@pam"
   # api_password: "ixelles1050"
    #api_host: "pve-pxs-sm2u-r5-33"
    #node: "{{ node }}"
    #vmid: "{{ vm_id }}"
    #scsi: "{{ scsi_map }}"
    #state: present
  #delegate_to: localhost

#- name: Start VM {{ vm_name }}
 # community.general.proxmox_kvm:
  #  api_user: "root@pam"
   # api_password: "ixelles1050"
    #api_host: "pve-pxs-sm2u-r5-33"
   # node: "{{ node }}"
    #vmid: "{{ vm_id }}"
    #state: started
 # delegate_to: localhost


- name: Create VM
  community.general.proxmox_kvm:
    api_user: "ansible@pam"
    api_password: "ixelles1050"
    api_host: "pve-pxs-sm2u-r5-33"
    node: "{{ proxmox_node }}" 
    vmid: "200"
    name: "vm-ubuntu-24-04"
    ostype: l26
    cores: "{{ cpu_cores }}"
    net:
      net0: 'virtio,bridge=vmbr0,tag=508'
    memory: "{{ memory }}"
    state: present

#- name: Create root disk
 # community.general.proxmox_disk:
  #  api_user: "{{ proxmox_api_user }}"
  #  api_password: "{{ proxmox_api_password }}"
  #  api_host: "{{ proxmox_api_host }}"
  #  vmid: "{{ vm_id }}"
  #  disk: "virtio0"
  #  size: "local-lvm:50G"
  #  format: raw
  #  state: present


- name: Create root disk
  community.general.proxmox_disk:
      api_user: "ansible@pam"
      api_password: "ixelles1050"
      api_host: "pve-pxs-sm2u-r5-33"
      vmid: "200"
      disk: "virtio0"
      size: "50"  # Disk size in GB as a string (no units)
      storage: "local-lvm"  # Use your LVM-thin pool name
      format: raw  # Optional, default is raw for LVM-thin pools
      state: present


- name: Create home disk
  community.general.proxmox_disk:
    api_user: "ansible@pam"
    api_password: "ixelles1050"
    api_host: "pve-pxs-sm2u-r5-33"
    vmid: "200"
    disk: "virtio1"
    size: "30"
    storage: "local-lvm"
    format: raw
    state: present

- name: Create opt disk
  community.general.proxmox_disk:
    api_user: "ansible@pam"
    api_password: "ixelles1050"
    api_host: "pve-pxs-sm2u-r5-33"
    vmid: "200"
    disk: "virtio2"
    size: "20"
    storage: "local-lvm"
    format: raw
    state: present

- name: Set boot order
  community.general.proxmox_kvm:
    api_user: "ansible@pam"
    api_password: "ixelles1050"
    api_host: "pve-pxs-sm2u-r5-33"
    vmid: "200"
    node: "pve-pxs-sm2u-r5-33"
    boot: "order=ide2;scsi0;net0"

- name: Start VM
  community.general.proxmox_kvm:
    api_user: "ansible@pam"
    api_password: "ixelles1050"
    api_host: "pve-pxs-sm2u-r5-33"
    vmid: "200"
    state: started



  
    

- name: Attach root disk to VM
  community.general.proxmox_disk:
    api_user: "ansible@pam"
    api_password: "ixelles1050"
    api_host: "pve-pxs-sm2u-r5-33"
    ansible.builtin.command:
      cmd: qm set 200 --scsi0 local-lvm:50
    delegate_to: "pve-pxs-sm2u-r5-33"
    vmid: "200"
    disk: "scsi0"
    size: "50000000000"  # Replace with desired disk size
    storage: "local-lvm"  # Replace with your storage pool
    format: raw
    state: present


- name: Attach ISO as CD-ROM
  community.general.proxmox_disk:
    api_user: "ansible@pam"
    api_password: "ixelles1050"
    api_host: "pve-pxs-sm2u-r5-33"
    node: "{{ proxmox_node }}"
    vmid: "200"
    disk: "ide2"
    storage: "local"  # Replace with your ISO storage pool
    file_path: "iso/ubuntu-24.04.1-live-server-amd64-autoinstall.iso"  # Path to ISO file in Proxmox
    media_type: cdrom
    state: present


- name: Create logical volume
  ansible.builtin.command:
     cmd: lvcreate -L 50G -n vm-200-disk-3 pve
  become: yes
