---
  #- name: Create VM
   # community.general.proxmox_kvm:
    #  api_user: "ansible@pam"
     # api_password: "ixelles1050"
      #api_host: "pve-pxs-sm2u-r5-33"
      #node: "{{ proxmox_node }}" 
      #vmid: "200"
      #name: "vm-ubuntu-24-04"
      #ostype: l26
      #cores: "{{ cpu_cores }}"
      #net:
       # net0: 'virtio,bridge=vmbr0,tag=508'
      #memory: "{{ memory }}"
      #state: present
  
  
  
  
  #- name: Set boot order
   # community.general.proxmox_kvm:
    #  api_user: "ansible@pam"
    #  api_password: "ixelles1050"
    #  api_host: "pve-pxs-sm2u-r5-33"
    #  vmid: "200"
    #  node: "pve-pxs-sm2u-r5-33"
    #  boot: "order=ide2;scsi0;net0"
  
  #- name: Start VM
   # community.general.proxmox_kvm:
    #  api_user: "ansible@pam"
     # api_password: "ixelles1050"
     # api_host: "pve-pxs-sm2u-r5-33"
     # vmid: "200"
     # state: started
  
  
  #- name: Attach root disk to VM
   # community.general.proxmox_disk:
    #  api_user: "ansible@pam"
    #  api_password: "ixelles1050"
    #  api_host: "pve-pxs-sm2u-r5-33"
    #  vmid: "200"
    #  disk: "scsi0"
    #  size: "50000"  # Replace with desired disk size
    #  storage: "local-lvm"  # Replace with your storage pool
    #  format: raw
    #  state: present
  
  #- name: Set VM disk using qm command
   # ansible.builtin.command:
    #  cmd: qm set 200 --scsi0 local-lvm:50
    #delegate_to: "pve-pxs-sm2u-r5-33"
  
  
  #- name: Attach ISO as CD-ROM
   # community.general.proxmox_disk:
    #  api_user: "ansible@pam"
     # api_password: "ixelles1050"
     # api_host: "pve-pxs-sm2u-r5-33"
     # node: "{{ proxmox_node }}"
     # vmid: "200"
     # disk: "ide2"
     # storage: "local"  # Replace with your ISO storage pool
     # file_path: "iso/ubuntu-24.04.1-live-server-amd64-autoinstall.iso"  # Path to ISO file in Proxmox
     # media_type: cdrom
     # state: present
  
- name: Création de la VM
  community.general.proxmox_kvm:
       api_user: "ansible@pam"
       api_password: "ixelles1050"
       api_host: "pve-pxs-sm2u-r5-33"
       node: "{{ proxmox_node }}"
       vmid: "151"
       name: "VM-ubuntu-2404"
       ostype: l26
       cores: 4
       sockets: 2
       memory: 4096
       bios: seabios
       machine: q35
       scsihw: virtio-scsi-pci  # Use VirtIO SCSI controller
       net:
         net0: "virtio,bridge=vmbr0,firewall=1,tag=508"
       boot: "order=ide2;scsi0;net0"  # Set boot order with SCSI disk
       ide:
         ide2: "local:iso/ubuntu-24.04.1-live-server-amd64-autoinstall.iso,media=cdrom"
       scsi:
         scsi0: "local-lvm:50G,iothread=1"  # Root disk (50GB)
         scsi1: "local-lvm:30G,iothread=1"  # Home disk (30GB)
         scsi2: "local-lvm:20G,iothread=1"  # Opt disk (20GB)
       state: present
   
- name: Attendre avant de démarrer la VM
  ansible.builtin.pause:
       seconds: 10
   
- name: Démarrer la VM
  community.general.proxmox_kvm:
       api_user: "ansible@pam"
       api_password: "ixelles1050"
       api_host: "pve-pxs-sm2u-r5-33"
       vmid: "151"
       state: started
   
- name: Mettre à jour l'ordre de démarrage après installation
  community.general.proxmox_kvm:
       api_user: "ansible@pam"
       api_password: "ixelles1050"
       api_host: "pve-pxs-sm2u-r5-33"
       node: "{{ proxmox_node }}"
       vmid: "151"
       boot: "order=scsi0;net0"  # Boot from the main SCSI disk after installation
       state: present